### ISSUE TITLE
Add the possibility to highlight several places on the protein model

### ISSUE THREAD

**Issue by ens-lgil** [PDBeurope/pdb-lite-mol#1]
Hi Mandar,

I was wondering if this would be possible to highlight several places on a protein model ?
For instance I would like to be able to highlight the positions 10-12, 25-28 and 53 on a protein model.
Actually in my use case it would be more likely to be something like highlighting the positions 5,32,58,96.

Thanks,
Laurent

**Comment by mandarsd** [comment]
Hi Laurent,

You can use the 'SelectExtractFocus' helper function to accomplish this. Here is a demo for your reference - https://embed.plnkr.co/c5K23wAX0TWexmIsLOVm/

Cheers,
Mandar

**Comment by ens-lgil** [comment]
Brilliant!
Thank you Mandar!

Laurent

**Comment by ens-lgil** [comment]
Hi Mandar,

Sorry, just a follow up question regarding the multiple selection: is it possible to colour the different elements selected on differents colours ?
e.g.:
- selection 1: residues 10 to 15 highlighted in blue
- selection 2: residues 22 to 24 highlighted in red
- selection 3: residue 35 highlighted in yellow
... and so on

This could be useful to differentiate the selected elements without having to move the mouse over them.

Cheers,
Laurent

**Comment by mandarsd** [comment]
Hi Laurent,

To accomplish this you'll have to do custom themes implementation. Currently you have to use some LiteMol core commands/methods for which we don't have any helper function in the component.

Here is the working demo - https://embed.plnkr.co/HmclfeEXY2diUEf6mQqA/

You can refer to LiteMol core documentation to check all the advance implementations you can do using the core library functions.
https://github.com/dsehnal/LiteMol/tree/master/examples
https://github.com/dsehnal/LiteMol/tree/master/examples/Commands
https://webchemdev.ncbr.muni.cz/LiteMol/Examples/Commands/

I have added the litemol-custom-theme.js script snippet in the demo from the commands example.

Hope this helps!

Cheers,
Mandar

**Comment by ens-lgil** [comment]
Hi Mandar,

Thank you very much for the demo! I added it to my [test](http://www.ebi.ac.uk/~lgil/tests/3d/) and it worked!

Cheers,
Laurent

**Comment by mandarsd** [comment]
Excellent! I'll close this issue then.

Cheers,
Mandar
