### ISSUE TITLE
screenshot button not working in google chrome browser

### ISSUE THREAD

**Issue by rishjain-iitr** [PDBeurope/pdb-lite-mol#2]
The screenshot button in the control tab is not functional in the Google Chrome web browser. Though it is working fine in other browsers like Firefox and Safari.

In the google chrome, clicking the screenshot button opens a new tab with (about:blank) URL.

Please try to provide the fix for this!

**Comment by mandarsd** [comment]
Thanks for pointing out the issue. I have added a fix. Please pull the updates.
